### ISSUE TITLE
Improving search so that it can look at keywords or description words also - User Story 1

### ISSUE THREAD

**Issue by zanzoonh** [CMU-17313Q/nodebb-f24-codehers#14]
Acceptance Criteria:
- The key/descirption words should be taken from multiple locations (title, description text etc)
    - Could try entering keywords found in descriptions but not in titles
- The search should prioritize the key/desciprtion words based on the frequency of the words.
- the keywords should appear only when written completely.
    - Keywords exactly matching should appear first in the results
- key/description words should be highlighted when found
- if the keywords aren’t found, the search function should displaly “no results found”

Dependent on issue #13

**Comment by AlAnoud2003** [comment]
Acceptance Criteria:
- The key/descirption words should be taken from multiple locations (title, description text etc)
    - Could try entering keywords found in descriptions but not in titles
- The search should prioritize the key/desciprtion words based on the frequency of the words.
- the keywords should appear only when written completely.
    - Keywords exactly matching should appear first in the results
- key/description words should be highlighted when found
- if the keywords aren’t found, the search function should displaly “no results found”
