### ISSUE TITLE
Creating the button to allow users to submit bugs / feedback - User Story 2

### ISSUE THREAD

**Issue by zanzoonh** [CMU-17313Q/nodebb-f24-codehers#15]
Acceptance Criteria:
-Users should be able to see a button for comments
-Users should be able to click it 
-Users should be directed/ pop-up a comment bar
-Users should be able to submit it through a button

**Comment by rmmahmou** [comment]
- A "Submit Bug/Feedback" button should be prominently visible on all relevant pages.
