### ISSUE TITLE
Taking in reported bugs / feedback from the user and storing it - User Story 2

### ISSUE THREAD

**Issue by zanzoonh** [CMU-17313Q/nodebb-f24-codehers#17]
Acceptance Criteria: 
-Users should be able to input feedback on bugs/errors
-After they submit it should be saved in a file that the developers can take a look at to address

**Comment by galishaq** [comment]
resons for delay:
- under estimation of each task effort 
- dependanicy on the issues before it 
- faced a lot of errors in implementing button
