### ISSUE TITLE
Work on the interface design for the 'Anonymous' button - User Story 3

### ISSUE THREAD

**Issue by Hakaabi** [CMU-17313Q/nodebb-f24-codehers#18]
Acceptance Criteria:

-The button should provide visual feedback when it is toggled on or off.
-The button should successfuly hide the user’s identity:
-The user’s name, email, profile picture shouldn’t show after clicking the button
-After posting/commenting, the user’s identity should remain hidden.

**Comment by AlAnoud2003** [comment]
Acceptance Criteria:
- The button should provide visual feedback when it is toggled on or off.
- The button should successfuly hide the user’s identity:
    - The user’s name, email, profile picture shouldn’t show after clicking the button
    - After posting/commenting, the user’s identity should remain hidden.
